#!/bin/bash
cmake -B build -DCMAKE_INSTALL_PREFIX=/usr/local -Dsimpleio_ENABLE_TESTS=OFF -S . -B build
cmake --build build
cmake --install build --prefix ./package-root
cpack --config build/CPackConfig.cmake
