name: CI

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push-image:
    name: Build docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            -f .devcontainer/Dockerfile \
            --push .

      - name: Fix permissions
        run: |
          sudo chown -R 0:0 ${{ github.workspace }}

      - name: Also tag and push :latest (only on main)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

  pre-commit:
    name: pre-commit
    needs: build-and-push-image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run pre-commit
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG
          docker run --rm -u root -v ${{ github.workspace }}:/workspace -w /workspace $IMAGE_NAME:$IMAGE_TAG bash -c "
            git config --global --add safe.directory /workspace && pre-commit run --all-files
          "

  build-and-test:
    name: Build and Test
    needs: pre-commit
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and run tests in devcontainer
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG
          docker run --rm -u root -v ${{ github.workspace }}:/workspace -w /workspace -e GITHUB_ACTIONS=1 $IMAGE_NAME:$IMAGE_TAG bash -c "
            ./scripts/build && \
            ./scripts/test
          "
      - name: Upload build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build

  analyze:
    name: Analyze
    needs: build-and-test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build

      - name: Run clang-tidy in devcontainer
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG
          docker run --rm -u root -v ${{ github.workspace }}:/workspace -w /workspace $IMAGE_NAME:$IMAGE_TAG bash -c "
            ./scripts/analyze
          "

  release:
    name: Release
    needs: build-and-push-image
    runs-on: ubuntu-22.04
    if: github.ref_type == 'tag'
    permissions:
      contents: write

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build debian package
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG
          docker run --rm --platform linux/${{ matrix.arch }} -u root -v ${{ github.workspace }}:/workspace -w /workspace $IMAGE_NAME:$IMAGE_TAG bash -c "
              ./scripts/package
            "

      - name: Upload .deb
        uses: softprops/action-gh-release@v1
        with:
          files: ./*_${{ matrix.arch }}.deb
